# Generated by Django 4.0.3 on 2022-03-12 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pamphlet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.CharField(blank=True, default='', max_length=1024)),
                ('visibility', models.CharField(choices=[('PRI', 'Private'), ('PUB', 'Public'), ('FRI', 'Friends Only')], default='PRI', max_length=3)),
                ('isDeleted', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
