# Generated by Django 4.0.3 on 2022-03-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamphlet', '0002_statusentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusentry',
            name='visibility',
            field=models.CharField(blank=True, choices=[('PRI', 'Private'), ('PUB', 'Public'), ('FRI', 'Friends Only')], default='PRI', max_length=3),
        ),
    ]
