# Generated by Django 4.0.3 on 2022-03-14 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pamphlet', '0004_friendrequestentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentFriendRequestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='pamphlet.friendrequestentry')),
            ],
        ),
    ]
