# Generated by Django 4.0.3 on 2022-03-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamphlet', '0005_currentfriendrequestentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequestentry',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
