# Generated by Django 4.0.3 on 2022-03-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamphlet', '0007_delete_currentfriendrequestentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequestentry',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='friendrequestentry',
            name='message',
            field=models.CharField(blank=True, default='', editable=False, max_length=256),
        ),
    ]
