# Generated by Django 4.0.3 on 2022-03-15 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pamphlet', '0009_alter_friendrequestentry_user_unilateralfriendship'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentUnilateralFriendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('friendship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pamphlet.unilateralfriendship')),
            ],
        ),
    ]
