# Generated by Django 4.0.3 on 2022-03-15 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pamphlet', '0010_currentunilateralfriendship'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrentUnilateralFriendship',
            new_name='UnilateralFriendshipRecord',
        ),
    ]
