# Generated by Django 4.0.3 on 2022-03-16 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pamphlet', '0014_unilateralfriendshiprecord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unilateralfriendshiprecord',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='unilateralfriendshiprecord',
            name='last_updated',
        ),
    ]
