# Generated by Django 4.0.3 on 2022-03-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamphlet', '0016_alter_unilateralfriendship_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendshipCreationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(blank=True, editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='unilateralfriendship',
            name='creation_date',
        ),
    ]
