# Generated by Django 4.0.3 on 2022-03-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamphlet', '0017_friendshipcreationrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshipcreationrecord',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
