# Generated by Django 4.0.3 on 2022-03-16 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pamphlet', '0018_alter_friendshipcreationrecord_creation_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendshipCreationRecord',
        ),
        migrations.RemoveField(
            model_name='unilateralfriendshiprecord',
            name='friendship',
        ),
        migrations.DeleteModel(
            name='UnilateralFriendship',
        ),
        migrations.DeleteModel(
            name='UnilateralFriendshipRecord',
        ),
    ]
