# Generated by Django 4.0.3 on 2022-03-20 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pamphlet.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pamphlet', '0023_alter_statusentryimage_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusentryimage',
            name='status_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pamphlet.statusentry'),
        ),
        migrations.CreateModel(
            name='AvatarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to=pamphlet.utils.getAvatarFilePathByUsername)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
