# Generated by Django 4.0.3 on 2022-03-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamphlet', '0025_likesentry_alter_avatarentry_avatar_image_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='likesentry',
            constraint=models.UniqueConstraint(fields=('user', 'status'), name='unique like record'),
        ),
    ]
