# Generated by Django 4.0.3 on 2022-03-25 18:36

from django.db import migrations, models
import pamphlet.utils


class Migration(migrations.Migration):

    dependencies = [
        ('pamphlet', '0037_alter_avatarentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatarentry',
            name='avatar_image',
            field=models.ImageField(blank=True, default='__defaults__/default-avatar-alien.png', null=True, upload_to=pamphlet.utils.getAvatarFilePathByUsername),
        ),
    ]
